# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 04:14
from __future__ import unicode_literals

import articulo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=articulo.models.get_dropbox_storage, upload_to=b''),
        ),
    ]
