# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_auto_20170225_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descrpcion', models.TextField()),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'categorias',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulo.Categoria'),
            preserve_default=False,
        ),
    ]
