# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 05:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import storages.backends.dropbox


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_auto_20170403_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.dropbox.DropBoxStorage(), upload_to=b''),
        ),
    ]
