# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0004_auto_20170227_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
