# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:33
from __future__ import unicode_literals

import articulo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0005_auto_20170227_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='introduccion',
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=articulo.models.upload_location, width_field='width_field'),
        ),
    ]
