# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.dropbox


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'required': '\xbfC\xfaal es el nombre de la ciudad?'}, max_length=50, validators=[django.core.validators.RegexValidator(message=b'Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')])),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'ciudades',
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'required': '\xbfC\xfaal es el nombre del pa\xeds?'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message=b'Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')])),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'paises',
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombres', models.CharField(error_messages={'required': '\xbfC\xfaal es tu nombre?'}, max_length=40, validators=[django.core.validators.RegexValidator(message=b'Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')])),
                ('apellidos', models.CharField(error_messages={'required': '\xbfC\xfaal es tu apellido?'}, max_length=40, validators=[django.core.validators.RegexValidator(message=b'Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')])),
                ('fecha_nacimiento', models.DateField(error_messages={'required': '\xbfEn qu\xe9 a\xf1o naciste'})),
                ('foto', models.ImageField(blank=True, height_field=128, storage=storages.backends.dropbox.DropBoxStorage(), upload_to=b'', width_field=128)),
                ('ciudad', models.ForeignKey(error_messages={'required': '\xbfD\xf3nde vives?'}, on_delete=django.db.models.deletion.PROTECT, to='usuario.Ciudad')),
            ],
            options={
                'db_table': 'perfiles',
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(error_messages={'required': '\xbfHa que pa\xeds pertenece la ciudad?'}, on_delete=django.db.models.deletion.CASCADE, to='usuario.Pais'),
        ),
    ]
